### PR TITLE
Update Digipeater.c

### PR DESCRIPTION
**Pull request by dl1mx**
Corrected SSID for destination address

### CODE REVIEW

**Comment by markqvist** [comment]
Thanks for the patch! Before I merge it, did you test it out on hardware and check that it works as expected?

**Comment by markqvist** [comment]
Ok, after reviewing your change, I'll just go ahead and merge this directly, but please do let me know if it was tested on hardware, and not just a "blind patch" ;)

**Comment by dl1mx** [comment]
Yes, it is 100% tested. I've seen the wrong SSID in UZ7OH softmodem while the micromodem was connected to the Baofeng. I patched the software, compiled anfd programmed again. After I've seen the correct APRS packet I created this patch. Thanks for the hard- and software project!

**Comment by markqvist** [comment]
Awesome! Great work! Thanks again for the fix!

**Pull request merged**
